#! /bin/bash

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
	echo "FAIBASE DEBIAN DEMO FAISERVER" ;;
    demohost)
	echo "FAIBASE DEBIAN DHCPC DEMO" ;;
    gnomehost)
	echo "FAIBASE DEBIAN DHCPC DEMO XORG GNOME";;
    atom*)
	echo "FAIBASE DEBIAN DHCPC DEMO" ;;
    opensuse-fai-test)
   	echo "FAIBASE GERMAN SUSE OPENSUSE103_32BIT";;
    *)
	echo "FAIBASE DHCPC DEBIAN" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB 
exit 0
