Document: fai-distributions
Title: Debian fai-distributions Manual
Author: <insert document author here>
Abstract: This manual describes what fai-distributions is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fai-distributions/fai-distributions.sgml.gz

Format: postscript
Files: /usr/share/doc/fai-distributions/fai-distributions.ps.gz

Format: text
Files: /usr/share/doc/fai-distributions/fai-distributions.text.gz

Format: HTML
Index: /usr/share/doc/fai-distributions/html/index.html
Files: /usr/share/doc/fai-distributions/html/*.html

  
