#! /bin/bash

set -e
. /usr/share/debconf/confmodule

[ -r /etc/default/fai ] && . /etc/default/fai

# check if installserver value is already set, otherwise set default 
if [ -z $installserver ] ; then
  db_get fai/installserver
  if [ "$RET" = "" ]; then
    db_set fai/installserver $(hostname)
  fi
else
  db_set fai/installserver $installserver
fi

db_input medium fai/installserver || true
db_go || true

if [ -z $mirrorhost ] ; then
  db_get fai/mirrorhost
  if [ "$RET" = "" ]; then
    db_set fai/mirrorhost ftp.debian.org
  fi
else
  db_set fai/mirrorhost $mirrorhost
fi

db_input medium fai/mirrorhost || true

db_go || true
