#!/usr/bin/perl -w

#*********************************************************************
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# A copy of the GNU General Public License is available as
# `/usr/share/common-licences/GPL' in the Debian GNU/Linux distribution
# or on the World Wide Web at http://www.gnu.org/copyleft/gpl.html. You
# can also obtain it by writing to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#*********************************************************************

use strict;

################################################################################
#
# @file shdd2-init
#
# @brief Initialize all variables and acquire the set of disks of the system.
#
# $Id$
#
# @author Christian Kern, Michael Tautschnig
# @date Sun Jul 23 16:09:36 CEST 2006
#
################################################################################

package FAI;

################################################################################
#
# @brief Enable debugging by setting $debug to a value greater than 0
#
################################################################################
$FAI::debug = 0;
defined( $ENV{debug} ) and $FAI::debug = $ENV{debug};

################################################################################
#
# @brief The lists of disks of the system
#
################################################################################
@FAI::disks = split( /\n/, $ENV{disklist} );
( $FAI::debug > 0 ) and print "disklist was:\n" . $ENV{disklist};

################################################################################
#
# @brief The variables later written to disk_var.sh
#
################################################################################
%FAI::disk_var = ();
$FAI::disk_var{"SWAPLIST"} = "";

################################################################################
#
# @brief The hash of all configurations specified in the disk_config file
#
# The structure is as follows:
# PHY_<DEVICE>
#   virtual (0|1)
#   disklabel STRING
#   bootable -1..n
#   partitions
#     <1..n>
#       size
#         extended (0|1)
#         preserve (0|1)
#         resize (0|1)
#         range
#         eff_size
#       number 1..n
#       maps_to_existing 1..n
#       start_byte
#       end_byte
#       mountpoint
#       mount_options
#       filesystem
#       fs_options
#       label
# VG_<NAME>
#   devices
#   estimated_size
#   volumes
#     <logical-volume-name>
#       size
#         preserve (0|1)
#         resize (0|1)
#         range
#         eff_size
#       mountpoint
#       mount_options
#       filesystem
#       fs_options
#       label
# RAID
#   volumes
#     <0..n>
#       mode
#       devices
#         /dev/<device-name>
#           options
#             spare (0|1)
#             missing (0|1)
#       mountpoint
#       mount_options
#       filesystem
#       fs_options
#       label
#
################################################################################
%FAI::configs = ();

################################################################################
#
# @brief The current disk configuration
#
# The structure is as follows:
# <DEVICE>
#   bios_cylinders
#   bios_heads
#   bios_sectors_per_track
#   sector_size
#   disklabel
#   begin_byte
#   end_byte
#   partitions
#     <1..n>
#       begin_byte
#       end_byte
#       count_byte
#       is_extended
#       filesystem
#
################################################################################
%FAI::current_config = ();

################################################################################
#
# @brief The current LVM configuration
#
# The structure is as follows:
# <VG>
#   physical_volumes
#   size
#   volumes
#     <lv-name>
#       size
#
################################################################################
%FAI::current_lvm_config = ();

################################################################################
#
# @brief The current RAID configuration
#
# The structure is as follows:
# <0..n>
#   devices
#   mode
#
################################################################################
%FAI::current_raid_config = ();

################################################################################
#
# @brief The list of commands to be executed
#
################################################################################
@FAI::commands = ();

1;

