#!/usr/bin/perl -w

use strict;

package FAI;

$FAI::debug = 1;

# getopt processing

#REMOVE THIS
# use a predefined list?

$ENV{disklist} = "hda
";
################
#

@FAI::disks = split( /\n/, $ENV{disklist} );

%FAI::configs = ();

%FAI::current_config = ();

@FAI::commands = ();

$FAI::parted_binary = "/sbin/parted -s";

1;

