#!/usr/bin/perl -w

use strict;

package FAI;

sub in_path
{
  my ($filesystem) = @_;

  my @path_list = split( ":", $ENV{"PATH"} );

  foreach my $p (@path_list)
  {
    ( -x "$p/mkfs.$filesystem" ) and return 0;
  }
  return 1;
}

sub print_hash
{
  ( $debug > 0 ) or return 0;

  my ( $hash_ref, $k ) = @_;
  $k = "$k>";

  foreach my $key ( keys %$hash_ref )
  {
    if ( ref( $hash_ref->{$key} ) )
    {
      print "$k KEY: $key VAL: hash\n";
      &print_hash( $hash_ref->{$key}, $k );
    }
    else
    {
      print "$k KEY: $key VAL: $hash_ref->{$key}\n";
    }
  }
}

1;

