#!/usr/bin/perl -w

#*********************************************************************
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# A copy of the GNU General Public License is available as
# `/usr/share/common-licences/GPL' in the Debian GNU/Linux distribution
# or on the World Wide Web at http://www.gnu.org/copyleft/gpl.html. You
# can also obtain it by writing to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#*********************************************************************

use strict;

################################################################################
#
# @file shdd2-lib
#
# @brief A small library of utility functions possibly useful in various places
#
# $Id$
#
# @author Christian Kern, Michael Tautschnig
# @date Sun Jul 23 16:09:36 CEST 2006
#
################################################################################

package FAI;

################################################################################
#
# @brief Test, whether @ref $cmd is available on the system using $PATH
#
# @param $cmd Command that is to be found in $PATH
#
# @return 1, if the command is found, else 0
#
################################################################################
sub in_path
{

  # initialize the parameter
  my ($cmd) = @_;

  # split $PATH into its components
  my @path_list = split( ":", $ENV{"PATH"} );

  # search all components of $PATH
  foreach my $p (@path_list)
  {

    # and test for $cmd being executable
    ( -x "$p/$cmd" ) and return 1;
  }
  return 0;
}

################################################################################
#
# @brief The structure, in which we hold informations about existing partitions
# and partitions we want to create a hold in hash of hashes. This debug function
# allows to recursivly print such a hash with all keys und subhashes
#
# @param hash_ref the reference to the hash, where we want to start printing
# the hash recursively
#
# @param k A helper variable, is only to be used for the recursion. The caller
# caller shoudn't set this one
#
################################################################################
sub print_hash
{

  # This function is for debugging purposes only
  ( $FAI::debug > 0 ) or return 0;

  # get the function parameters
  my ( $hash_ref, $k ) = @_;

  # append a > for showing the depth in the hash of hashes
  $k = "$k>";

  # print all keys
  foreach my $key ( keys %$hash_ref )
  {

    # if there is another hash, recursively call the function with this hash
    if ( ref( $hash_ref->{$key} ) )
    {
      print "$k KEY: $key VAL: hash\n";
      &print_hash( $hash_ref->{$key}, $k );
    }
    else
    {
      print "$k KEY: $key VAL: $hash_ref->{$key}\n";
    }
  }
}

1;

