#!/usr/bin/perl -w

use strict;

package FAI;

sub in_path
{
  my ($filesystem) = @_;

  my @path_list = split(":", $ENV{"PATH"});

  foreach my $p (@path_list)
  {
    if( -x $p."/mkfs.$filesystem")
    {
      return 1;
    }
  }
  return 0;
}

1;

