#! /bin/bash

fcopy -Bv /etc/dhcp3/dhcpd.conf /etc/default/tftpd-hpa # not needed /etc/apache2/conf.d
fcopy -Bvr /etc/fai
fcopy -Bvn /etc/make-live.conf

#/etc/fai/fai.conf /etc/fai/make-fai-nfsroot.conf
fcopy /etc/apt-proxy/apt-proxy-v2.conf /etc/fai/sources.list
# use the same sources.list for the server itself and the clients
#cp -a $target/etc/fai/apt $target/etc/
fcopy -Bvr /etc/apt

