#!/bin/bash

if [ ! -f $target/root/setup ] ; then
fcopy -r /etc/
fcopy /var/lib/tftpboot/pxelinux.cfg/default
copy $target/etc/apt/sources.list $target/etc/fai/apt/sources.list
mkdir -p $target/lib/init/rw
mv $target/etc/pamldap.conf $target/etc/pam_ldap.conf
chmod +x  $target/etc/rc2.d/S99postinstall-faiserver
# pxeboot

if [ -f $target/usr/lib/syslinux/pxelinux.0 ]; then
    cp $target/usr/lib/syslinux/pxelinux.0 $target/var/lib/tftpboot/
else
    echo "hm. pxeboot file not found. tyr again?"
fi
cp -rp /var/lib/roll-out $target/var/lib/


# Apache/php configs
# FixMe Set ServerName in config
chmod -R a+r $target/etc/apache2 $target/etc/php5

# ldap-account-manager

chown -R www-data $target/etc/ldap-account-manager

# wiki

if [! $LOGDIR/boot.log ]; then
    cp /tmp/fai/boot.log $LOGDIR/boot.log
 
fi

# Fixme: boot.log normally gets lost...

cp /tmp/fai/boot.log $target/var/log/fainetdevinfo.log
rm $target/etc/fai/apt/sources.list
cp $target/etc/apt/sources.list $target/etc/fai/apt/sources.list

# Fixme: why the old kernel is installed?

perl -pi -e's/2.6.17/2.6.18/g' $target/etc/fai/make-fai-nfsroot.conf

# process the config files; change IP Adresses in there


    for i in `cat /tmp/fai/boot.log`; do
	export $i
    done

    export NETWORK=`echo $IPADDR | cut -d\. -f1,2,3`
    
    export hostname=`hostname`

    echo "Debug: changing system config files to match ip $IPADDR"

    gunzip /var/lib/roll-out/mysql.dump.gz

    for i in /etc /var/lib/tftpboot /var/lib/roll-out/mysql.dump /srv/fai/config/; do 
	find $i -type f -exec perl -pi -e'use Env qw(IPADDR);s/192.168.0.1/$IPADDR/g' {} \;
	find $i -type f -exec perl -pi -e'use Env qw(IPADDR);s/faiserver/$IPADDR/g' {} \;
	find $i -type f -exec perl -pi -e'use Env qw(NETMASK);s/255.255.255.0/$NETMASK/g' {} \;
	find $i -type f -exec perl -pi -e'use Env qw(GATEWAYS);s/192.168.0.254/$GATEWAYS/g' {} \;
	find $i -type f -exec perl -pi -e'use Env qw(BROADCAST);s/192.168.0.255/$BROADCAST/g' {} \;
	find $i -type f -exec perl -pi -e'use Env qw(hostname);s/faiserver-cd/$hostname/g' {} \;
	find $i -type f -exec perl -pi -e'use Env qw(NETWORK);s/192.168.0/$NETWORK/g' {} \;
	
    done

echo "update done." > $target/root/setup
else
    echo "Postinstall already done."
    exit 0
fi