#!/bin/sh
PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin

DISTRIBUTION="mandriva"

if [ `id -u` -ne 0 ]; then
    echo "Run this program as root."
    exit 9
fi

# option e currently does nothing
while getopts vc:f: opt ; do
    case "$opt" in
        c) cfdir=$OPTARG ;;
        v) verbose=1 ; v=-v ;;
        f) cfg=$OPTARG ;;
        ?) exit 5 ;; # error in option parsing
    esac
done

set -e

# source fai.conf and make-fai-nfsroot.conf
[ -z "$cfdir" ] && cfdir=/etc/fai
if [ ! -d "$cfdir" ]; then
    echo "$cfdir is not a directory"
    exit 6
fi

[ "$verbose" ] && echo "Using configuration files from directory $cfdir"
if [ -n "$cfg" ]; then
    . $cfdir/$cfg
else
    . $cfdir/fai.conf
fi


. /etc/fai-distributions/${DISTRIBUTION}.conf

if [ -z "$NFSROOT" ]; then
    echo "\$NFSROOT is not set. Please check your settings in $cfdir/fai.conf."
    exit 4
fi

# workaround/timesaver: fetch a pre-build base image
if ! [ -z $BASE_IMAGE ];then
    cd /tmp/
    if [ -e $BASE_IMAGE ]; then
        rm $BASE_IMAGE
    fi
    wget $BASE_IMAGE_ARCHIVE/$BASE_IMAGE

    mv $BASE_IMAGE $NFSROOT/var/tmp/
    echo "base image $BASE_IMAGE successfully fetched and placed in nfsroot"
    exit 0
fi

# FIXME: can/should probably be defined somewhere in /etc/fai?
TMP_CHROOT_DIR=`mktemp -d /tmp/fai/${DISTRIBUTION}_debootstrap.XXXXXX`
echo "TMPDIT is $TMP_CHROOT_DIR"


# FIXME: doesn't work yet
#rpmstrap --include=$BASE_EXTRA_PACKAGES mandriva10 $TMP_CHROOT_DIR $MANDRIVA_MIRROR
rpmstrap mandriva10 $TMP_CHROOT_DIR $MANDRIVA_MIRROR

echo "Creating base-$DISTRIBUTION.tgz"

cd $TMP_CHROOT_DIR
tar cfz $NFSROOT/var/tmp/base-$DISTRIBUTION.tgz *

rm -r $TMP_CHROOT_DIR
