#! /bin/sh

# $Id$

# create a writeable area on the install client

if [ ! -e /proc/self ]
then
    mount -n -t proc proc /proc
fi

# start devfsd if needed
if [ -c /dev/.devfsd ]; then
    /sbin/devfsd /dev
fi

# perhaps we already have a ramdisk set up
temp=`mktemp -q -p /tmp`
if [ $? -eq 0 ]
then
   echo "create_ramdisk: /tmp is already writable, magic!"
   rm $temp
   mkdir /tmp/etc
else
    # if we have shm use it as ramdisk
    mount -t tmpfs tmpfs /tmp || {
        ramdevice=/dev/ram0
        mke2fs -q -m 0 $ramdevice && echo "ramdisk $ramdevice created"
        mount -n $ramdevice /tmp
    }
    mkdir -p /tmp/etc /tmp/target
fi

mkrw /dev /var/run /var/log /var/lock /var/lib/discover /etc/sysconfig
