#! /bin/sh

# Author: Holger Levsen <debian@layer-acht.org>

case "$1" in
  start)
	# if we do "fai install", we need from fai-nfsroot:
	# ./lib/mkrw
	# ./lib/load_keymap_consolechars
	# ./lib/create_resolv_conf
	# 
	# and we need to 
	# echo do_init_tasks=1 >> /etc/fai/fai.conf
 	#
	# so we go for softupdates...
	#
	unset LANG
        sh -xv /usr/sbin/fai  -N softupdate
	;;
  *)
  	echo doing nothing
	;;
esac


