#! /usr/bin/perl

# faimond-gui: graphical FAI monitor daemon
#
# This script is part of FAI (Fully Automatic Installation)
# Copyright (C) 2007 Thomas Lange, lange@informatik.uni-koeln.de
# Universitaet zu Koeln

use Tk;
use Tk::HList;
use Tk::ItemStyle;
use Tk::Balloon;

open(INP, "<$ARGV[0]") or die "Ooops::";


#@tasklist = qw/hostname confdir defclass action partition mountdisks extrbase mirror debconf prepareapt instsoft configure chboot savelog faiend/;

@tasklist = qw/hostname confdir defclass partition extrbase debconf instsoft configure savelog faiend/;

$tasklist[0] = 'hostname';
$rowcount = 0;
%message = ( 'TASKBEGIN' => 'BEG', 'TASKEND' => 'END');

sub xgetinp {
  $line = <INP>;
#  warn "INPUT received $line";
  hostentry($line);
  return 0;
}

sub hostentry {

  my $str = shift(@_);
  my ($host,$startstop,$task,$code) = split(/\s+/,$str);


#Style entries
#

#  $backcolor="#d6e3e9";
#  $forecolor="#FFFFFF";
#  $headercolor="#000000";
#  $regularcolor="#3c97cc";
#  $failcolor="#942a2a";
#  $successcolor="#6cb85a";
#  $font="Sans 15";


  $backcolor="#76716f";
  $forecolor="#ffffff";
  $headercolor="#ffffff";
  $regularcolor=$backcolor;
  $failcolor=$backcolor;
  $successcolor=$backcolor;
  $font="Sans 15";


  $imgsuccess = $top->Photo(-file=>"icons/ok3d.gif");
  $imgfail = $top->Photo(-file=>"icons/fail3d.gif");
  $imgbegin = $top->Photo(-file=>"icons/beg3d.gif");
  $imghost = $top->Photo(-file=>"icons/bar.gif");
  my $fail = $hlist->ItemStyle("imagetext",
                            -foreground => $forecolor,
                            -background => $failcolor,
                            -font => $font,
                        );

  my $success = $hlist->ItemStyle("imagetext",
                            -foreground => $forecolor,
                            -background => $successcolor,
                            -font => $font,
                        );

  my $regular = $hlist->ItemStyle("imagetext",
                            -foreground => $forecolor,
                            -background => $regularcolor,
                            -font => $font,
                        );
  my $headerstyle = $hlist->ItemStyle("imagetext", 
			    -bg=>$backcolor,
			    -fg=>$headercolor,
			    -font=>$font
			);
#   $balloonstatus = $top->Balloon();
#   $balloonstatus->attach($top,-msg=>"status",-balloonposition=>"mouse");


#  warn "hostentry: $host $startstop $task $code\n";

  unless (exists $row{$host}) {
    # add host, first column
    $row{$host} = $rowcount++;

    $hlist->add($row{$host},-state=>"disabled");
    $hlist->itemCreate($row{$host}, 0, -itemtype => "imagetext" , -text => $host , -style=>$headerstyle, -image=>$imghost);
#    return;
  }

  # remove old information when doing an reinstallation
  if ($startstop eq 'check') {
    foreach (1 .. $#tasklist) {
#        warn "XXX $row{$host} X $_\n";
        $hlist->itemCreate($row{$host}, $_, -text => '');
    }
    return;
  }

#  warn "create: $row{$host} X  $task{$task} X $startstop $message{$startstop} $code\n";
  unless (exists $task{$task}) {
    # do not show unknown tasks
    return;
  }

  $message = ($startstop =~ /TASKEND/) ?  $message="$message{$startstop} $code": $message{$startstop};
  
  if ($message eq 'END 0') {
#    $hlist->itemCreate($row{$host}, $task{$task}, -text => $message ,-itemtype=>"imagetext",-image=>$imgsuccess);
    $hlist->itemCreate($row{$host}, $task{$task}, -text=>'' ,-itemtype=>"imagetext",-image=>$imgsuccess);
    $hlist->itemConfigure($row{$host}, $task{$task}, -itemtype=>"imagetext",-style=>$success);

  } elsif ($message eq 'BEG') {
#    $hlist->itemCreate($row{$host}, $task{$task}, -text => $message ,-itemtype=>"imagetext",-image=>$imgbegin);
    $hlist->itemCreate($row{$host}, $task{$task}, -text => '' ,-itemtype=>"imagetext",-image=>$imgbegin);
    $hlist->itemConfigure($row{$host}, $task{$task}, -itemtype=>"imagetext",-style=>$regular);
  } else {
#    $hlist->itemCreate($row{$host}, $task{$task}, -text => $message ,-itemtype=>"imagetext",-image=>$imgfail);
    $hlist->itemCreate($row{$host}, $task{$task}, -text => '' ,-itemtype=>"imagetext",-image=>$imgfail);
    $hlist->itemConfigure($row{$host}, $task{$task}, -itemtype=>"imagetext",-style=>$fail);
  }

}

$top = new MainWindow;
$top->configure(-background=>"#76716f");
$hlist = $top->Scrolled("HList",
            -header => 1,
            -columns => $#tasklist+1,
            -scrollbars => 'oe',
            -width => 94,
            -selectbackground => '#76716f',
	    -background=>'#76716f',
	    -selectborderwidth=>0,
	    -selectmode=>'single',
	    -highlightthickness=>0,
	    -relief=>'flat',
	    -borderwidth=>0,
               )->pack(-expand => 1, -fill => 'both');
$top->fileevent(INP,'readable', [\&xgetinp]);
foreach (@tasklist) {
#-text => $_
  $headline = $top->Photo(-file=>"icons/" . $_ . ".gif"); 
  $hlist->header('create', $n++, -itemtype=>"imagetext" ,-headerbackground=>"#76716f",-borderwidth=>0,-relief=>"flat",-image=>$headline );
#  $hlist->header('configure', $b++ , -bitmap=>$imghost); 
  $task{$_} = $tcounter++;
}




MainLoop();
