#! /bin/bash
#
# $FAI_CONFIGDIR/hooks/subroutines

# Custom FAI subroutines to install vserver children

# from http://faiwiki.informatik.uni-koeln.de/index.php/User:BrianShowalter/Using_FAI_to_install_Linux-vservers
#
# Written by Brian Showalter
# 11 Feb 2006

task_vschild_defclass() {
        # Reevaluate classes
        fai-class -T $FAI/class $LOGDIR/FAI_CLASSES
        classes=$(< $LOGDIR/FAI_CLASSES)

    # define classes as: a.b.c.d for cfengine -D
    # this doesn't work without echo
    cfclasses=$(echo $classes)
    cfclasses=${cfclasses// /.}
    [ "$debug" ] && echo "cfclasses: $cfclasses"
}

task_vschild_create() {
        echo "Creating vserver $vsname"
        local removepkgs="sparc-utils,dhcp-client,lilo,makedev,pcmcia-cs,ppp,pppconfig,pppoe"
        removepkgs="${removepkgs},pppoeconf,setserial,syslinux,fdutils,libpcap0"
        removepkgs="${removepkgs},pciutils,ipchains,iptables,jove,nano"

        chroot $VSHOST_FAI_ROOT /usr/sbin/vserver $vsname build -m debootstrap \
                --hostname $childhost --interface $childdev:$childip/$childprefix -- \
                -d sarge -m http://$mirrorhost/debian -- --exclude="$removepkgs"
}

task_vschild_updatebase() {
        if [ "$FAI_ACTION" = "install" ]; then
                # Some packages must access /proc even in chroot environment
                mount -t proc proc $FAI_ROOT/proc

            # if libc is upgraded init u is called in chroot environment and
            # then init will eat up much cpu time
            fai-divert -a /sbin/init /usr/sbin/liloconfig /usr/sbin/invoke-rc.d
            # fake some more programs
#           fai-divert -a /etc/init.d/nis /sbin/start-stop-daemon
#           cp /sbin/start-stop-daemon $FAI_ROOT/sbin/start-stop-daemon
        fi

        # update the apt-get information inside the nfsroot
        export aptopt='-y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'
        $ROOTCMD apt-get $aptopt update
        $ROOTCMD apt-get $aptopt check
        [ $? -ne 0 ] && $ROOTCMD apt-get $aptopt -f install </dev/null
        $ROOTCMD dpkg -C
        [ $? -ne 0 ] && yes '' | $ROOTCMD dpkg --configure -a
        # using the above value, causes an error: "dpkg need action"
        export aptopt=
        $ROOTCMD apt-get $aptopt -f -y dist-upgrade </dev/null
        # update dpkg info which packages are available
        tmp=$($ROOTCMD mktemp)
        $ROOTCMD apt-cache dumpavail > $FAI_ROOT/$tmp
        $ROOTCMD dpkg --update-avail $tmp
        rm -f $FAI_ROOT/$tmp
}

task_vschild_install() {
        task debconf
        task prepareapt
        task vschild_updatebase
        task instsoft
        task configure
	task savelog
}

task_savelog() {

    [ -d $target/var/log/fai ] || mkdir -p $target/var/log/fai
    [ -d $target/var/log/fai ] && fai-savelog -l
    [ -f $LOGDIR/FAI_CLASSES ] && cp -p $LOGDIR/FAI_CLASSES $target/var/log/fai
    [ -f $LOGDIR/variables.sh ] && cp -p $LOGDIR/variables.sh $target/var/log/fai
    [ "x$diskvar" != "x" -a "$diskvar" != "/var/log/fai/disk_var.sh" -a -f "$diskvar" ] && cp -p $diskvar $target/var/log/fai
    fai-savelog -r
}

