#! /bin/sh

# echo architecture, OS name and distribution in upper case.
# Do NOT remove these lines

uname -s | tr '[:lower:]' '[:upper:]'

if [ `which dpkg` ]; then
    dpkg --print-installation-architecture | tr /a-z/ /A-Z/
else    
    uname -i | tr '[:lower:]' '[:upper:]'
fi

[ -f /boot/RUNNING_FROM_FAICD ] && echo "FAICD"
exit 0
