#! /bin/sh

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    demohost)
	echo "FAIBASE DHCPC DEMO EXIM" ;;
    gnomehost)
	echo "FAIBASE DHCPC DEMO XFREE GNOME EXIM";;
    *)
	echo "FAIBASE DHCPC" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB 
exit 0
