#! /bin/bash

$ROOTCMD wget -P/tmp http://debmirror/mirrors/binary-packages/apache-tomcat-6.0.13.tar.gz
$ROOTCMD tar xvfz /tmp/apache-tomcat-6.0.13.tar.gz -C /opt/

echo "TODO: create a start script, and enable it to be run at system startup"
exit 1
