#!/bin/sh

[ ! -d /var/www/html/phpMyAdmin-2.10.2-english ] && {
	[ -f /tmp/phpMyAdmin-2.10.2-english.tar.bz2 ] && rm /tmp/phpMyAdmin-2.10.2-english.tar.bz2
	# FIXME: better find wget option to overwrite target!
	$ROOTCMD wget -P/tmp http://debmirror/mirrors/binary-packages/phpMyAdmin-2.10.2-english.tar.bz2
	$ROOTCMD tar xfj /tmp/phpMyAdmin-2.10.2-english.tar.bz2 -C /var/www/html/
}

[ -d /var/www/html/myadmin ] && rm /var/www/html/myadmin
$ROOTCMD ln -s /var/www/html/phpMyAdmin-2.10.2-english /var/www/html/myadmin

