#!/bin/bash

# (c) 2002-2006 Henning Glawe <glaweh@debian.org>

### BEGIN SUBROUTINE INFO
# Provides-Var:
# Requires-Var:    $FAI_CONFIG_SRC $FAI $LOGDIR
# Suggests-Var:
# Short-Description: get $FAI from an svn repository.
### END SUBROUTINE INFO

# matched string: "svn://user@host/svnpath"
protocol=$(expr match "$FAI_CONFIG_SRC" '\([^:]*\)://')
username=$(expr match "$FAI_CONFIG_SRC" '[^:]*://\([^@]*\)@')
svnpath=$(expr match "$FAI_CONFIG_SRC" '[^:]*://[^@]\+@\(\S\+\)')

case $protocol in
	svn)
		svnurl="svn://$svnpath"
		;;
	svn+http)
		svnurl="http://$svnpath"
		;;
	*)
		echo "get-config-dir-svn: protocol $protocol not implemented"
		exit 1
		;;
esac
		
[ -n "$username" ] && user="--username $username"

if [ -d "$FAI/.svn" ] ; then
   echo "Updating SVN in $FAI"
   cd $FAI
   svn -q up $user > $LOGDIR/getconf.log
else 
   echo "Checking out SVN"
   svn -q co $user \
     $svnurl $FAI > $LOGDIR/getconf.log
fi
