#! /bin/bash
# 
#     dry-run connect script -- instead of updating real clients, it outputs
#                               random strings from FAI to see if the updater
#                               catches the status correctly
#
#     fai-updater - start and supervise fai softupdates on many hosts
#     Copyright (C) 2004-2006  Henning Glawe <glaweh@debian.org>
# 
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# 
WAITTIME="$[ $RANDOM*10/32768 ]"
echo $1 is waiting for $WAITTIME seconds
sleep $WAITTIME
#randomly fail to start
[ "$[ $RANDOM*10/32768 ]" -lt 1 ] && exit
cat <<-EOF
    -----------------------------------------------------
      FAIVERSIONSTRING
      Fully Automatic Installation for Debian GNU/Linux

      Copyright (c) 1999-2002, Thomas Lange
              lange@informatik.uni-koeln.de
    -----------------------------------------------------
EOF

sleep 2

#randomly fail in the middle
[ "$[ $RANDOM*10/32768 ]" -lt 1 ] && exit

# randomly produce apt errors
[ "$[ $RANDOM*10/32768 ]" -lt 1 ] && echo "An error occured" 
sleep 3
echo "Saving log files to z1"
sleep 2
