#! /usr/bin/perl
# 
#     get_hostlist -- get netgroup members, print the hostnames line-by-line
# 
#     fai-updater - start and supervise fai softupdates on many hosts
#     Copyright (C) 2004-2006  Henning Glawe <glaweh@debian.org>
# 
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# 

die "usage: $0 <netgroup>" if ($#ARGV<0);

# get the netgroup output
$_=`getent netgroup $ARGV[0]`;
chomp;
# strip off the key (first entry)
s/^\S+//;
# remove brackets and commas
s/[\(\)\,]//g;
# remove anything after the short hostname
@hostlist=map {s/\..*$//; $_ } split;
# write out newline-delimited list of hostnames
print join("\n", @hostlist) . "\n";
