#!/bin/sh
PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin

DISTRIBUTION="centos3"

if [ `id -u` -ne 0 ]; then
    echo "Run this program as root."
    exit 9
fi

# option e currently does nothing
while getopts vc:f: opt ; do
    case "$opt" in
        c) cfdir=$OPTARG ;;
        v) verbose=1 ; v=-v ;;
        f) cfg=$OPTARG ;;
        ?) exit 5 ;; # error in option parsing
    esac
done

set -e

# source fai.conf and make-fai-nfsroot.conf
[ -z "$cfdir" ] && cfdir=/etc/fai
if [ ! -d "$cfdir" ]; then
    echo "$cfdir is not a directory"
    exit 6
fi

[ "$verbose" ] && echo "Using configuration files from directory $cfdir"
if [ -n "$cfg" ]; then
    . $cfdir/$cfg
else
    . $cfdir/fai.conf
fi


. /etc/fai-distributions/${DISTRIBUTION}.conf

if [ -z "$NFSROOT" ]; then
    echo "\$NFSROOT is not set. Please check your settings in $cfdir/fai.conf."
    exit 4
fi


# FIXME: can/should probably be defined somewhere in /etc/fai?
TMPDIR="/tmp/fai/${DISTRIBUTION}_debootstrap/"
echo "TMPDIT is $TMPDIR"

rpmstrap centos3 $TMPDIR $MIRROR

echo "Creating base-$DISTRIBUTION.tgz"

cd $TMPDIR
tar cfz $NFSROOT/var/tmp/base-$DISTRIBUTION.tgz *

#chroot $TMPDIR umount /dev
chroot $TMPDIR umount /.dev
 
