#!/bin/sh
#
#  This script disables the hardware clock.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$target

#
#  Disable the startup scripts from all runlevels.
#
# FIXME: only for Debian - what to do in FEDORA?
[ -f ${prefix}/etc/init.d/hwclock.sh ] && chmod -x ${prefix}/etc/init.d/hwclock.sh

#chmod -x ${prefix}/etc/init.d/hwclockfirst.sh

exit 0
