#!/bin/sh
#
#  This script does two things:
#
#  1. Sets the console type for the first terminal to 'console'.
#  2. Comments out all virtual terminals which aren't on the first console.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$target


#
# Do the transformation.
#
sed -i -e 's/^\([2-6].*:respawn*\)/#\1/' -e 's/^T/#\t/' ${prefix}/etc/inittab

