#! /bin/sh

# (c) Thomas Lange, 2001-2006, lange@debian.org

ifclass XORG && {
    fcopy -M /etc/X11/xorg.conf
#    [ -n "$VIDEODRIVER" ] || VIDEODRIVER=vesa
#    grep -q %%VIDEODRIVER%% $target/etc/X11/xorg.conf &&
#    perl -pi.orig -pe "s/%%VIDEODRIVER%%/$VIDEODRIVER/" $target/etc/X11/xorg.conf
}

exit 0
