#! /bin/bash

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
	echo "FAIBASE DEMO FAISERVER" ;;
    demohost)
	echo "FAIBASE DHCPC DEMO" ;;
    gnomehost)
	echo "FAIBASE DHCPC DEMO XORG GNOME";;
    atom*)
	echo "FAIBASE DHCPC DEMO" ;;
    rhel5-demo)
	#echo "DIST-RHEL_5 FAIBASE DHCPC XENU" ;;
	echo "DEBUG DIST-RHEL_5 FAIBASE DHCPC RHEL-DEMO-COMMON RHEL-DEMO-WEBSERVER RHEL-DEMO-NAMESERVER RHEL-DEMO-DBSERVER XENU" ;;
    xen-tools-test)
	echo "FAIBASE DHCPC XENU" ;;
    *)
	echo "FAIBASE DHCPC BLA" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB 
exit 0
