#! /bin/bash

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    rhel5-demo-web)
	echo "DEBUG DIST-RHEL_5 FAIBASE DHCPC"
	echo "RHEL-DEMO-COMMON RHEL-DEMO-SOFTUPDATE RHEL-DEMO-TOMCAT RHEL-DEMO-WEBSERVER"
	echo "XENU"
	;;
    rhel5-demo-dns)
	echo "DEBUG DIST-RHEL_5 FAIBASE DHCPC"
	echo "RHEL-DEMO-COMMON RHEL-DEMO-NAMESERVER RHEL-DEMO-SOFTUPDATE"
	echo "RHEL-DEMO-KERNEL RHEL-NETINSTALL"
	;;
    rhel5-demo-db)
	echo "DEBUG DIST-RHEL_5 FAIBASE DHCPC"
	echo "RHEL-DEMO-COMMON RHEL-DEMO-DBSERVER RHEL-DEMO-SOFTUPDATE RHEL-DEMO-WEBSERVER"
	echo "XENU"
	;;
    *)
	echo "FAIBASE DHCPC" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB 
exit 0
