#! /bin/sh

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
	echo "FAIBASE DEMO FAISERVER" ;;
    demohost)
	echo "FAIBASE DHCPC DEMO" ;;
    gnomehost)
	echo "FAIBASE DHCPC DEMO XFREE GNOME";;
    atom*)
	echo "FAIBASE DHCPC DEMO" ;;

# For building VServer hosts and children

    vshost)
        echo "FAIBASE VSHOST VSCOMMON";;
    vschild1)
        echo "VSCHILD VSCOMMON APACHE" && exit 0;;
    vschild2)
        echo "VSCHILD VSCOMMON MYSQL" && exit 0;;
    vschild3)
        echo "VSCHILD VSCOMMON POSTFIX" && exit 0;;

    *)
	if ifclass VSCHILD
	then
	    echo "VSCOMMON";
        else
	    echo "FAIBASE DHCPC" 
        fi;;
esac

(ifclass I386 || ifclass AMD64) && ( ifclass VSCHILD || echo GRUB )
exit 0
