#!/bin/sh
set -e

case "$1" in
	purge|remove)
    update-alternatives \
      --remove default.plymouth /lib/plymouth/themes/fai/fai.plymouth

    rmdir /lib/plymouth/themes || :
    rmdir /lib/plymouth || :

    if which update-initramfs >/dev/null 2>&1
    then
      update-initramfs -u
    fi
	;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

    *)
	echo "$0 called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
