#!/bin/bash

# get-fai-cvs -- get fai configuration directory $FAI from a cvs repository.
# (c) 2002-2006 Henning Glawe

pushd &>/dev/null

# matched string: "cvs+ssh://user@blah/blubb/lalala module=tag"
PROTOCOL=$(expr match "$FAI_CONFIG_SRC" '\(.*\)://.*')
CVS_PATH=$(expr match "$FAI_CONFIG_SRC" '.*://\(\S\+\)\s\+.*')
CVS_MODULE=$(expr match "$FAI_CONFIG_SRC" '.*://.*\s\+\([^=]*\).*')
CVS_TAG=$(expr match "$FAI_CONFIG_SRC" '.*=\(.*\)')

case $PROTOCOL in
	cvs+ssh)
		export CVS_RSH=ssh
		export CVSROOT=":ext:$CVS_PATH"
		;;
	cvs)
		export CVSROOT=":pserver:$CVS_PATH"
		;;
	*)
		echo "get-config-dir-cvs: protocol $PROTOCOL not implemented"
		exit 1
		;;
esac
		
[ -n "$CVS_TAG" ] && TAG="-r $CVS_TAG"

FAI_CONFIG_AREA=$FAI_ROOT/var/lib/fai/config
    
if [ -d "$FAI_CONFIG_AREA/CVS" ] ; then
   echo "Config found at $FAI_CONFIG_AREA: Copying"
   cp -a $FAI_CONFIG_AREA/. $FAI
   echo "Updating CVS"
   cd $FAI
   cvs -q up -P $CVS_TAG -d -C > $LOGDIR/getconf.log
else 
   echo "Checking out CVS"
   cd /tmp
   cvs -q co -P -d $(basename "$FAI") \
     $CVS_TAG $CVS_MODULE > $LOGDIR/getconf.log
fi
popd &>/dev/null
