#! /bin/bash

error=0 ; trap "error=$((error|1))" ERR

set -a

# during softupdate use this file
[ -r $target/var/log/fai/disk_var.sh ] && . $target/var/log/fai/disk_var.sh

# if class NOMBR is defined, write boot loader into root partition, not into mbr
ifclass NOMBR && BOOT_DEVICE=$BOOT_PARTITION

if [ ! -z $BOOT_DEVICE ]; then
	grub-install --no-floppy --root-directory=$target $BOOT_DEVICE
	GROOT=$(device2grub $BOOT_PARTITION)
	perl -pi -e 's/#(\w+)#/$ENV{$1}/' $2
	ifclass DIST-DEBIAN && $ROOTCMD /usr/sbin/update-grub
	# TODO: how to update grub on other distributions?
	echo "Grub installed on $BOOT_DEVICE on $GROOT"	
else
	echo "BOOT_DEVICE empty - not running grub-instll"
fi

exit $error

